# Generated by Django 5.1.2 on 2024-11-02 14:29

import django.db.models.deletion
import news.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.newsPath)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['created_on', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.eventPath)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=100)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.session')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
