# Generated by Django 5.1.2 on 2024-11-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
    ]
