# Generated by Django 5.1.2 on 2024-11-03 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_class_created_by_alter_classname_created_by_and_more'),
        ('examination', '0002_question_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cbtresult',
        #     name='answers',
        #     field=models.JSONField(blank=True, default=dict),
        # ),
        # migrations.AddField(
        #     model_name='cbtresult',
        #     name='per_exam_scores',
        #     field=models.JSONField(blank=True, default=dict),
        # ),
        migrations.AlterField(
            model_name='cbtcategory',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbt_categories', to='base.class'),
        ),
        migrations.AlterField(
            model_name='cbtexam',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.class'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'academic_director']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
