# Generated by Django 5.1.2 on 2024-12-04 17:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_course_name_alter_customuser_role_and_more'),
        ('examination', '0003_cbtresult_answers_cbtresult_per_exam_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtresult',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cbtresult',
            name='per_exam_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cbtresult',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Past-Question', 'Past-Question'), ('Teacher-Question', 'Teacher-Question'), ('Comprehension', 'Comprehension')], default='Past-Question', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='base.studentprofile'),
        ),
    ]
