# Generated by Django 5.1.2 on 2024-12-11 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_cbtresult_answers_cbtresult_per_exam_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cbt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_questions', to='examination.cbtexam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='examination.exam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_practice_questions', to='examination.exampractice'),
        ),
    ]
