# Generated by Django 5.1.2 on 2024-12-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_alter_question_cbt_alter_question_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='cbt',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam_practice',
        ),
        migrations.AddField(
            model_name='question',
            name='cbt',
            field=models.ManyToManyField(blank=True, related_name='cbt_questions', to='examination.cbtexam'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_practice',
            field=models.ManyToManyField(blank=True, related_name='exam_practice_questions', to='examination.exampractice'),
        ),
    ]
