# Generated by Django 5.1.2 on 2024-12-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_remove_question_cbt_remove_question_exam_practice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ManyToManyField(blank=True, related_name='questions', to='examination.exam'),
        ),
    ]
