# Generated by Django 5.1.2 on 2024-11-02 13:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('absent_with_reason', 'Absent with Reason')], default='absent', max_length=40, null=True)),
                ('reason_for_absence', models.TextField(blank=True, null=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.class')),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin', 'mini_tech_support', 'tech_support', 'superuser']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_taken', to=settings.AUTH_USER_MODEL)),
                ('school_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.schoolbranch')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='base.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('absent_with_reason', 'Absent with Reason')], default='absent', max_length=40)),
                ('reason_for_absence', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'tech_support', 'mini_tech_support', 'superuser']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance_taken', to=settings.AUTH_USER_MODEL)),
                ('school_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.schoolbranch')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.session')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='base.teacherprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
