# Generated by Django 5.1.2 on 2024-11-03 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classname',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_names', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='previllageduserprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previllaged_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='manager',
            field=models.OneToOneField(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='techsupportprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_support_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'academic_director', 'tech_support', 'mini_tech_support', 'superuser', 'manager', 'mini_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
