# Generated by Django 5.1.2 on 2024-12-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_class_created_by_alter_classname_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('academic_director', 'Academic Director'), ('data_entry', 'Data Entry'), ('manager', 'Manager'), ('guest', 'Guest'), ('mini_tech_support', 'Mini Tech Support'), ('mini_manager', 'Mini Manager'), ('parent', 'Parent'), ('project_manager', 'Project Manager'), ('school_staff', 'School Staff'), ('teacher', 'Teacher'), ('student', 'Student'), ('tech_support', 'Tech Support')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='local_government_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='previllageduserprofile',
            name='local_government_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='local_government_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='local_government_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techsupportprofile',
            name='local_government_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
